
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package horeilly1101.Parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int RBRACK = 8;
  public static final int PLUS = 2;
  public static final int RPAREN = 6;
  public static final int TRIG = 17;
  public static final int LN = 11;
  public static final int LBRACK = 7;
  public static final int SQRT = 13;
  public static final int VARIABLE = 16;
  public static final int CARROT = 10;
  public static final int LPAREN = 5;
  public static final int LOG = 12;
  public static final int COMMA = 14;
  public static final int NUMBER = 18;
  public static final int ECON = 15;
  public static final int EOF = 0;
  public static final int DIVIDE = 9;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "DIVIDE",
  "CARROT",
  "LN",
  "LOG",
  "SQRT",
  "COMMA",
  "ECON",
  "VARIABLE",
  "TRIG",
  "NUMBER"
  };
}

