
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------
package horeilly1101.Parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  int CARROT = 8;
  int MINUS = 3;
  int DIVIDE = 7;
  int LN = 9;
  int NUMBER = 16;
  int TRIG = 15;
  int VARIABLE = 14;
  int EOF = 0;
  int PLUS = 2;
  int ECON = 13;
  int COMMA = 12;
  int error = 1;
  int RPAREN = 6;
  int SQRT = 11;
  int TIMES = 4;
  int LPAREN = 5;
  int LOG = 10;
  String[] terminalNames = new String[] {
    "EOF", "error", "PLUS", "MINUS", "TIMES", "LPAREN", "RPAREN", "DIVIDE",
    "CARROT", "LN", "LOG", "SQRT", "COMMA", "ECON", "VARIABLE", "TRIG", "NUMBER"
  };
}

