
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.deriv.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  int TIMES = 4;
  int RBRACK = 8;
  int PLUS = 2;
  int RPAREN = 6;
  int TRIG = 17;
  int LN = 11;
  int LBRACK = 7;
  int SQRT = 13;
  int VARIABLE = 16;
  int CARROT = 10;
  int LPAREN = 5;
  int LOG = 12;
  int COMMA = 14;
  int NUMBER = 18;
  int ECON = 15;
  int EOF = 0;
  int DIVIDE = 9;
  int MINUS = 3;
  int error = 1;
}